import PAGE_NAME from "@/constants/route-name.js";

export const AUTHENTICATION_MIDDLEWARE = "authentication";

export const BUSINESS_EMPLOYEE_MIDDLEWARE = [
  PAGE_NAME.PROJECT.LIST,
  PAGE_NAME.PROJECT.DETAILS,
  PAGE_NAME.PROJECT.CREATE,
  PAGE_NAME.PROJECT.EDIT,
  PAGE_NAME.CONTRACT.DETAILS,
  PAGE_NAME.CONTRACT.CREATE,
  PAGE_NAME.SITE_SURVEY.DETAILS,
  PAGE_NAME.CUSTOMER.LIST,
  PAGE_NAME.CUSTOMER.CREATE,
  PAGE_NAME.CUSTOMER.DETAILS,
];

export const RESOURCE_MANAGER_MIDDLEWARE = [
  PAGE_NAME.PROJECT.LIST,
  PAGE_NAME.PROJECT.DETAILS,
  PAGE_NAME.PROJECT.EDIT,
  PAGE_NAME.CONTRACT.DETAILS,
  PAGE_NAME.SITE_SURVEY.DETAILS,
  PAGE_NAME.PLANNING.LIST,
  PAGE_NAME.PLANNING.DETAILS,
  PAGE_NAME.PROGRESS.DETAILS,
  PAGE_NAME.CONSTRUCT_LOG.VIEW,
  PAGE_NAME.RESOURCE_MOBILIZATION.LIST,
  PAGE_NAME.RESOURCE_ALLOCATION.LIST,
  PAGE_NAME.CONSTRUCT_LOG.DETAILS,
  PAGE_NAME.INSPECTION_REPORT.LIST,
  PAGE_NAME.INSPECTION_REPORT.DETAILS,
  PAGE_NAME.INVENTORY.LIST,
  PAGE_NAME.RESOURCE.HUMAN.LIST,
  PAGE_NAME.RESOURCE.HUMAN.DETAILS,
  PAGE_NAME.RESOURCE.MATERIAL.LIST,
  PAGE_NAME.RESOURCE.MATERIAL.DETAILS,
  PAGE_NAME.RESOURCE.MACHINE.LIST,
  PAGE_NAME.RESOURCE.MACHINE.DETAILS,
];

export const TECHNICAL_MANAGER_MIDDLEWARE = [
  PAGE_NAME.PROJECT.LIST,
  PAGE_NAME.PROJECT.DETAILS,
  PAGE_NAME.PROJECT.EDIT,
  PAGE_NAME.CONTRACT.DETAILS,
  PAGE_NAME.SITE_SURVEY.DETAILS,
  PAGE_NAME.SITE_SURVEY.CREATE,
  PAGE_NAME.PLANNING.LIST,
  PAGE_NAME.PLANNING.DETAILS,
  PAGE_NAME.PROGRESS.DETAILS,
  PAGE_NAME.RESOURCE_MOBILIZATION.LIST,
  PAGE_NAME.RESOURCE_ALLOCATION.LIST,
  PAGE_NAME.CONSTRUCT_LOG.VIEW,
  PAGE_NAME.CONSTRUCT_LOG.DETAILS,
  PAGE_NAME.INSPECTION_REPORT.LIST,
  PAGE_NAME.INSPECTION_REPORT.DETAILS,
  PAGE_NAME.INVENTORY.LIST
];

export const CONSTRUCTION_MANAGER_MIDDLEWARE = [
  PAGE_NAME.PROJECT.LIST,
  PAGE_NAME.PROJECT.DETAILS,
  PAGE_NAME.PROJECT.EDIT,
  PAGE_NAME.CONTRACT.DETAILS,
  PAGE_NAME.SITE_SURVEY.DETAILS,
  PAGE_NAME.PLANNING.LIST,
  PAGE_NAME.PLANNING.DETAILS,
  PAGE_NAME.PLANNING.CREATE,
  PAGE_NAME.PROGRESS.DETAILS,
  PAGE_NAME.CONSTRUCT_LOG.VIEW,
  PAGE_NAME.CONSTRUCT_LOG.CREATE,
  PAGE_NAME.CONSTRUCT_LOG.DETAILS,
  PAGE_NAME.INSPECTION_REPORT.LIST,
  PAGE_NAME.INSPECTION_REPORT.DETAILS,
  PAGE_NAME.INVENTORY.LIST
];

export const QUALITY_ASSURANCE_MIDDLEWARE = [
  PAGE_NAME.PROJECT.LIST,
  PAGE_NAME.PROJECT.DETAILS,
  PAGE_NAME.PROJECT.EDIT,
  PAGE_NAME.CONTRACT.DETAILS,
  PAGE_NAME.SITE_SURVEY.DETAILS,
  PAGE_NAME.PLANNING.LIST,
  PAGE_NAME.PLANNING.DETAILS,
  PAGE_NAME.PROGRESS.DETAILS,
  PAGE_NAME.CONSTRUCT_LOG.VIEW,
  PAGE_NAME.CONSTRUCT_LOG.DETAILS,
  PAGE_NAME.INSPECTION_REPORT.LIST,
  PAGE_NAME.INSPECTION_REPORT.DETAILS,
  PAGE_NAME.INSPECTION_REPORT.CREATE,
];

export const EXECUTIVE_BOARD_MIDDLEWARE = [
  PAGE_NAME.CUSTOMER.LIST,
  PAGE_NAME.CUSTOMER.CREATE,
  PAGE_NAME.CUSTOMER.DETAILS,
  PAGE_NAME.PROJECT.LIST,
  PAGE_NAME.PROJECT.EDIT,
  PAGE_NAME.PROJECT.DETAILS,
  PAGE_NAME.CONTRACT.DETAILS,
  PAGE_NAME.SITE_SURVEY.DETAILS,
  PAGE_NAME.PLANNING.LIST,
  PAGE_NAME.PLANNING.DETAILS,
  PAGE_NAME.PROGRESS.DETAILS,
  PAGE_NAME.CONSTRUCT_LOG.VIEW,
  PAGE_NAME.CONSTRUCT_LOG.DETAILS,
  PAGE_NAME.RESOURCE_MOBILIZATION.LIST,
  PAGE_NAME.RESOURCE_ALLOCATION.LIST,
  PAGE_NAME.INSPECTION_REPORT.LIST,
  PAGE_NAME.INSPECTION_REPORT.DETAILS,
  PAGE_NAME.INVENTORY.LIST,
  PAGE_NAME.RESOURCE.HUMAN.LIST,
  PAGE_NAME.RESOURCE.HUMAN.DETAILS,
  PAGE_NAME.RESOURCE.MACHINE.LIST,
  PAGE_NAME.RESOURCE.MACHINE.DETAILS,
  PAGE_NAME.RESOURCE.MATERIAL.LIST,
  PAGE_NAME.RESOURCE.MATERIAL.DETAILS,
];

export const CONSTRUCTION_EMPLOYEE_MIDDLEWARE = [
  PAGE_NAME.PROJECT.LIST,
  PAGE_NAME.PROJECT.DETAILS,
  PAGE_NAME.PROJECT.EDIT,
  PAGE_NAME.CONTRACT.DETAILS,
  PAGE_NAME.SITE_SURVEY.DETAILS,
  PAGE_NAME.PLANNING.LIST,
  PAGE_NAME.PLANNING.DETAILS,
  PAGE_NAME.PROGRESS.DETAILS,
  PAGE_NAME.INSPECTION_REPORT.LIST,
  PAGE_NAME.INSPECTION_REPORT.DETAILS,
  PAGE_NAME.INVENTORY.LIST,
]; //

export const ADMIN_MIDDLEWARE = [
  PAGE_NAME.RESOURCE.HUMAN.LIST,
  PAGE_NAME.RESOURCE.HUMAN.CREATE,
  PAGE_NAME.RESOURCE.HUMAN.DETAILS,
  PAGE_NAME.RESOURCE.MACHINE.LIST,
  PAGE_NAME.RESOURCE.MACHINE.DETAILS,
  PAGE_NAME.RESOURCE.MACHINE.CREATE,
  PAGE_NAME.RESOURCE.MATERIAL.CREATE,
  PAGE_NAME.RESOURCE.MATERIAL.LIST,
  PAGE_NAME.RESOURCE.MATERIAL.DETAILS,
  PAGE_NAME.USER.CREATE,
  PAGE_NAME.USER.LIST,
  PAGE_NAME.USER.DETAILS,
] ; // done

export const USER_MIDDLEWARE = [
  PAGE_NAME.PROFILE,
  PAGE_NAME.LOGIN,
  PAGE_NAME.HOME
]
